name: mirror
on:
  schedule:
      - cron: 20,50 6-8 * * 1-5
  workflow_dispatch:
jobs:
  mirror:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        
      - name: Download files
        run: |
          CURRENT_YEAR=$(date +%Y)
          CURRENT_MONTH=$(date +%Y/%m)
          LAST_MONTH_Y=$(date -d "$(date +%Y-%m-01) -1 month" +%Y)
          LAST_MONTH=$(date -d "$(date +%Y-%m-01) -1 month" +%Y/%m)

          echo "CURRENT_YEAR = ${CURRENT_YEAR}"
          echo "CURRENT_MONTH = ${CURRENT_MONTH}"
          echo "LAST_MONTH_Y = ${LAST_MONTH_Y}"
          echo "LAST_MONTH = ${LAST_MONTH}"

          URL_CURRENT="https://mazda1micro1vaka.yakiuchi.com/diary/${CURRENT_MONTH}.html"
          URL_LAST="https://mazda1micro1vaka.yakiuchi.com/diary/${LAST_MONTH}.html"

          mkdir -p diary/${YEAR}
          mkdir -p diary/${LAST_MONTH_Y}
          curl -sf "$URL_CURRENT" > diary/${CURRENT_MONTH}.html || true
          curl -sf "$URL_LAST" > diary/${LAST_MONTH}.html || true
          
      - name: Commit and push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Fetch latest version" && git push)
